name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 1 - Install Dependencies
        run: pnpm install

      - name: 2 - Check Lint
        run: pnpm lint

      - name: 3 - Check Tests
        run: pnpm test
        env:
          API_URL: "http://localhost:3000"
          TOKEN_API_KEY: "example-token"
          NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: "example-key"
          NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID: "example-id"
